# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Image To Block Matrix
#' 
#' Splits an image into its blocks of a given size (typically 8x8) and returns them as a nested list.
#' The list contains the blocks in a [[row]][[column]] pattern, i.e. the inner list contains the rows, the outer list the columns.
#' 
#' @param image list of integer matrix of pixel values
#' @param blockwidths vector containing width of the blocks per channel
#' @param blockheights vector containing height of the blocks per channel
#' 
#' @return the image  containing all 8x8 blocks in a matrix form
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
imageToBlocks <- function(image, blockheights = as.integer( c(8,8,8)), blockwidths = as.integer( c(8,8,8))) {
    .Call('_jpegToolbox_imageToBlocks', PACKAGE = 'jpegToolbox', image, blockheights, blockwidths)
}

#' Block Matrix to Image Wrapper
#' 
#' Joins the blocks of an image to form the image again.
#' 
#' @param image list of integer matrix of pixel values
#' 
#' @return the merged image
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
blocksToImage <- function(image) {
    .Call('_jpegToolbox_blocksToImage', PACKAGE = 'jpegToolbox', image)
}

#' matrix of blocks to list of blocks
#' 
#' Transforms matrix of blocks to list of blocks
#' 
#' @param image list of list of integer matrices of pixel values
#' 
#' @return list of integer matrices
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
imageMatrixToList <- function(image) {
    .Call('_jpegToolbox_imageMatrixToList', PACKAGE = 'jpegToolbox', image)
}

#' To Block List
#' 
#' Splits an image into its blocks of a given size (typically 8x8) and returns them as a list.
#' The list contains the blocks column-wise, i.e. the first column of blocks is outputted first.
#' 
#' @param image list of integer matrix of pixel values
#' @param blockwidth width of a block
#' @param blockheight height of a block
#' 
#' @return the image  containing all 8x8 blocks in a list form
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
imageToBlocks_list <- function(image, blockheight = 8L, blockwidth = 8L) {
    .Call('_jpegToolbox_imageToBlocks_list', PACKAGE = 'jpegToolbox', image, blockheight, blockwidth)
}

#' RGB to YCbCr conversion
#'
#' Converts from RGB colour space to YCbCr.
#' To avoid floating point arithmetic the constants are scaled up by 2^16.
#' See jccolor.c of libjpeg for more details.
#'
#' @param R red pixel value in the range of 0..255
#' @param G green pixel value in the range of 0..255
#' @param B blue pixel value in the range of 0..255
#'
#' @return vector of Y, Cb and Cr values
#'
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#'
RGBtoYCbCr_cpp <- function(R, G, B) {
    .Call('_jpegToolbox_RGBtoYCbCr_cpp', PACKAGE = 'jpegToolbox', R, G, B)
}

#' YCbCr to RGB conversion
#'
#' Converts from YCbCr colour space to RGB.
#' To avoid floating point arithmetic the constants are scaled up by 2^16.
#' See jdcolor.c of libjpeg for more details.
#'
#' @param Y luminance pixel value in the range of 0..255
#' @param Cb blue chrominance pixel value in the range of 0..255
#' @param Cr red chrominance value in the range of 0..255
#'
#' @return vector of R, G and B values
#'
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#'
YCbCrtoRGB_cpp <- function(Y, Cb, Cr) {
    .Call('_jpegToolbox_YCbCrtoRGB_cpp', PACKAGE = 'jpegToolbox', Y, Cb, Cr)
}

#' Image conversion from RGB to YCbCr
#'
#' Converts an image from RGB colorspace to YCbCr.
#' Requires that all three channels have the same resolution.
#'
#' @param image list of matrices with R, G and B values
#'
#' @return list of matrices with Y, Cb and Cr values
#'
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#'
RGBtoYCbCr_image_cpp <- function(image) {
    .Call('_jpegToolbox_RGBtoYCbCr_image_cpp', PACKAGE = 'jpegToolbox', image)
}

#' Image conversion from YCbCr to RGB
#'
#' Converts an image from YCbCr colorspace to RGB.
#' Requires that all three channels have the same resolution.
#'
#' @param image list of matrices with Y, Cb and Cr values
#'
#' @return list of matrices with R, G and B values
#'
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#'
YCbCrtoRGB_image_cpp <- function(image) {
    .Call('_jpegToolbox_YCbCrtoRGB_image_cpp', PACKAGE = 'jpegToolbox', image)
}

#' kronecker Delta
#' 
#' Returns 1 if both inputs are the same and 0 if not
#' 
#' @param i first integer
#' @param j second integer
#' 
#' @return 1 if both integer are identical and 0 if not
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
kroneckerDelta <- function(i, j) {
    .Call('_jpegToolbox_kroneckerDelta', PACKAGE = 'jpegToolbox', i, j)
}

#' 1D DCT matrix
#' 
#' Generate the 1D DCT matrix
#' 
#' @param N size of sequence to be transformed
#' 
#' @return 1D DCT matrix
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
DCT1dmatrix_cpp <- function(N = 8L) {
    .Call('_jpegToolbox_DCT1dmatrix_cpp', PACKAGE = 'jpegToolbox', N)
}

DCT1d_cpp <- function(x, inverted = 0L) {
    .Call('_jpegToolbox_DCT1d_cpp', PACKAGE = 'jpegToolbox', x, inverted)
}

DCT2d_cpp <- function(x, inverted = 0L) {
    .Call('_jpegToolbox_DCT2d_cpp', PACKAGE = 'jpegToolbox', x, inverted)
}

DCTimage_cpp <- function(image, inverted = 0L, DCTscaling = 0L) {
    .Call('_jpegToolbox_DCTimage_cpp', PACKAGE = 'jpegToolbox', image, inverted, DCTscaling)
}

DCTimage_cpp_plain <- function(image, inverted = 0L) {
    .Call('_jpegToolbox_DCTimage_cpp_plain', PACKAGE = 'jpegToolbox', image, inverted)
}

#' Clip values to jpeg Range
#' 
#' Transforms a pixel value to fit in the range [0..255]
#' 
#' @param x pixel value
#' 
#' @return truncated pixel value
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
clipToJpegRange <- function(x) {
    .Call('_jpegToolbox_clipToJpegRange', PACKAGE = 'jpegToolbox', x)
}

#' Current libjpeg Version
#' 
#' Returns the current libjpeg compatibility version
#' 
#' @return current libjpeg compatibility version
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
getLibjpegVersion <- function() {
    .Call('_jpegToolbox_getLibjpegVersion', PACKAGE = 'jpegToolbox')
}

#' Rounding in C
#' 
#' Exposes the round function of C to R. In contrast to the R alternative it rounds 0.5 up.
#' 
#' @param x value to be rounded
#' 
#' @return rounded value
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
roundC_wrapper <- function(x) {
    .Call('_jpegToolbox_roundC_wrapper', PACKAGE = 'jpegToolbox', x)
}

#' Jpeg Quantization of image
#' 
#' applies a given quantization table to an image
#' 
#' @param image image object of class jpegImage
#' @param quantizationTable list of quantization tables for luminance and optionally chrominance
#' 
#' @return quantized image
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
quantize <- function(image, quantizationTable) {
    .Call('_jpegToolbox_quantize', PACKAGE = 'jpegToolbox', image, quantizationTable)
}

#' Jpeg dequantize of image
#' 
#' Dequantizes the compressed image using the quantization Tables provided in the object.
#' 
#' @param image image object of class jpegImage
#' 
#' @return dequantized image
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
#' @export
dequantize <- function(image) {
    .Call('_jpegToolbox_dequantize', PACKAGE = 'jpegToolbox', image)
}

readDCT_file <- function(filename, dequantize) {
    .Call('_jpegToolbox_readDCT_file', PACKAGE = 'jpegToolbox', filename, dequantize)
}

readDCT_memory <- function(rawImage, dequantize) {
    .Call('_jpegToolbox_readDCT_memory', PACKAGE = 'jpegToolbox', rawImage, dequantize)
}

readJpeg_file <- function(filename, fancyUpsampling) {
    .Call('_jpegToolbox_readJpeg_file', PACKAGE = 'jpegToolbox', filename, fancyUpsampling)
}

readJpeg_memory <- function(rawImage, fancyUpsampling) {
    .Call('_jpegToolbox_readJpeg_memory', PACKAGE = 'jpegToolbox', rawImage, fancyUpsampling)
}

#' Subsample image wrapper
#' 
#' Reduces the chrominance values of an image according to the provided subsampling factors.
#' 
#' @param image list of integer matrix of pixel values, typically an object of class jpegImage
#' @param subsampling subsampling factors in the form c(H1, V1, H2, V2, H3, V3)
#' 
#' @return image with subsampled Cb and Cr channels
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
subsampling_simple <- function(image, subsampling) {
    .Call('_jpegToolbox_subsampling_simple', PACKAGE = 'jpegToolbox', image, subsampling)
}

#' Upsample image
#' 
#' Extrapolate the reduced chrominance values of an image according to the provided subsampling factors in order to reconstruct the original image.
#' 
#' @param image list of integer matrix of pixel values, typically an object of class jpegImage
#' 
#' @return image with upsampled Cb and Cr channels
#' 
#' @author Matthias Carnein \email{Matthias.Carnein@@uni-muenster.de}
#' 
upsampling_simple <- function(image) {
    .Call('_jpegToolbox_upsampling_simple', PACKAGE = 'jpegToolbox', image)
}

subsampling_fancy8 <- function(image, subsampling) {
    .Call('_jpegToolbox_subsampling_fancy8', PACKAGE = 'jpegToolbox', image, subsampling)
}

upsampling_fancy8 <- function(image) {
    .Call('_jpegToolbox_upsampling_fancy8', PACKAGE = 'jpegToolbox', image)
}

upsampling_fancy6 <- function(image) {
    .Call('_jpegToolbox_upsampling_fancy6', PACKAGE = 'jpegToolbox', image)
}

writeJpeg_file <- function(image, quality, DCTmethod, subsampling, force_baseline, optimize_coding, progressive, smoothing, fancyDownsampling, filename) {
    invisible(.Call('_jpegToolbox_writeJpeg_file', PACKAGE = 'jpegToolbox', image, quality, DCTmethod, subsampling, force_baseline, optimize_coding, progressive, smoothing, fancyDownsampling, filename))
}

writeJpeg_memory <- function(image, quality, DCTmethod, subsampling, force_baseline, optimize_coding, progressive, smoothing, fancyDownsampling) {
    .Call('_jpegToolbox_writeJpeg_memory', PACKAGE = 'jpegToolbox', image, quality, DCTmethod, subsampling, force_baseline, optimize_coding, progressive, smoothing, fancyDownsampling)
}

